version: 2.1
orbs:
    node: circleci/node@5.0.2
    jira: circleci/jira@1.3.1

jobs:
    api_tests:
        executor: node/default
        steps:
            - checkout
            - node/install-packages:
                  pkg-manager: npm
            - run:
                  command: npm run test:report
                  name: Run tests
                  environment:
                      JEST_JUNIT_OUTPUT_DIR: ./reports/
            - store_test_results:
                  path: ./reports/
            - persist_to_workspace:
                  root: ~/project
                  paths:
                      - .

    # deploy: # this can be any name you choose
    #   executor: heroku/default
    #   steps:
    #     - attach_workspace:
    #         at: ~/project
    #     - heroku/deploy-via-git:
    #         force: true # force push when pushing to the heroku remote, see: https://devcenter.heroku.com/articles/git

workflows:
    run_tests:
        jobs:
            - api_tests:
                  post-steps:
                      - jira/notify
